logspout:
  image: gliderlabs/logspout:v3
  command: 'syslog://logstash:5000'
  links:
    - logstash
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock'

logstash:
  image: ludekvesely/logstash-json
  environment:
    - LOGSPOUT=ignore
    - DROP_NON_JSON=false
    - STDOUT=true
  ports:
    - "5000:5000"
  links:
    - elasticsearch

kibana:
  image: kibana
  environment:
    - LOGSPOUT=ignore
  links:
    - elasticsearch
  ports:
    - '5601:5601'

elasticsearch:
  image: elasticsearch
  environment:
    - LOGSPOUT=ignore