version: '2'
services:
    hub:
        image: selenium/hub:3.3.1
        ports:
          - "4444:4444"
        environment:
          - "GRID_MAX_SESSION=16"
    firefox:
        image: selenium/node-firefox:3.3.1
        links:
          - "hub:hub"
        environment:
          - "HUB_PORT_4444_TCP_ADDR=hub"
          - "HUB_PORT_4444_TCP_PORT=4444"
    chrome:
        image: selenium/node-chrome:3.3.1
        links:
          - "hub:hub"
        environment:
          - "HUB_PORT_4444_TCP_ADDR=hub"
          - "HUB_PORT_4444_TCP_PORT=4444"
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.0.1
        restart: always
        depends_on:
            - postgres
            - redis
        links:
            - hub:hub
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.0.1
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.0.1
        restart: always
        depends_on:
            - webserver
        links:
            - hub:hub
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: scheduler

    worker:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.0.1
        restart: always
        depends_on:
            - scheduler
        links:
            - hub:hub
        ports:
            - "8793:8793"
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: worker


