version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"

    webserver:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.1.1
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - ./dags:/workspace/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.1.1
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.1.1
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/workspace/airflow/dags
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: registry.cn-hangzhou.aliyuncs.com/brucedone/airflow:v0.1.1
        restart: always
        depends_on:
            - scheduler
        ports:
            - "8793:8793"
        volumes:
            - ./dags:/workspace/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - C_FORCE_ROOT=true
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: worker


